apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allow-ingress.yaml
  - certificate.yaml
  - deny-all-authz.yaml
  - gateway.yaml
  - issuer.yaml
  - strict-mtls.yaml
  - waf.yaml
